# -*- coding: utf-8 -*-
"""generate_golden_texts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jhw_HtH-He0hZPua8M9Yj6Spnfpr_oPL
"""

# !pip install -q transformers accelerate bitsandbytes sentencepieceb
# !pip install --upgrade transformers
# !pip install --upgrade accelerate bitsandbytes

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_id = "Qwen/Qwen3.5-4B"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    quantization_config=bnb_config,
    dtype=torch.float16,
    trust_remote_code=True
)

def build_prompt(emotion="Felicidade"):
  return f"""
Gere 2 textos curtos (1–3 frases) que expressem fortemente a emoção: {emotion}.

Requisitos:
- Cada texto deve representar um contexto diferente (ex: trabalho, família, redes sociais, etc.)
- Varie o estilo (formal, informal, introspectivo, narrativo)
- Evite frases genéricas
- Use linguagem natural em português

Emoção: {emotion}
"""

def generate_text(emotion, temperature=0.8, max_new_tokens=200):
    prompt = build_prompt(emotion)

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        temperature=temperature,
        top_p=0.9,
        do_sample=True
    )

    text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return text

emotion = "alegria"

output = generate_text(emotion)

print(output)