# -*- coding: utf-8 -*-
"""albertina_emotions_oof.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3UT6Ziax_ByTS2ctbeyCa-8HFZjtF_W
"""

# !pip install -q transformers datasets accelerate scikit-learn torch

import os
import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

df = pd.read_csv("/content/go_emotions_treated.csv")

df['BASE_TEXT_PT'] = df['BASE_TEXT_PT'].fillna("").astype(str)

emotions = [
    'admiration','amusement','anger','annoyance','approval','caring',
    'confusion','curiosity','desire','disappointment','disapproval',
    'disgust','embarrassment','excitement','fear','gratitude','grief',
    'joy','love','nervousness','optimism','pride','realization','relief',
    'remorse','sadness','surprise','neutral'
]

X = df["BASE_TEXT_PT"]
y = df[emotions]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.8, random_state=42
)

class CBTrainer(Trainer):
    def __init__(self, class_weights, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = torch.tensor(class_weights).float()

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=0):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        device = logits.device
        labels = labels.float().to(device)
        weights = self.class_weights.to(device)

        weights_for_samples = weights.unsqueeze(0) * labels
        weights_for_samples = weights_for_samples.sum(1).unsqueeze(1)
        weights_for_samples = weights_for_samples.repeat(1, labels.size(1))

        loss = F.binary_cross_entropy_with_logits(
            logits, labels, weight=weights_for_samples
        )

        return (loss, outputs) if return_outputs else loss

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    probs = 1 / (1 + np.exp(-logits))
    preds = (probs > 0.5).astype(int)

    precision_macro, recall_macro, f1_macro, _ = precision_recall_fscore_support(
        labels, preds, average="macro"
    )

    precision_micro, recall_micro, f1_micro, _ = precision_recall_fscore_support(
        labels, preds, average="micro"
    )

    precision_weighted, recall_weighted, f1_weighted, _ = precision_recall_fscore_support(
        labels, preds, average="weighted"
    )

    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "f1_macro": f1_macro,
        "f1_micro": f1_micro,
        "f1_weighted": f1_weighted,
        "precision_macro": precision_macro,
        "precision_micro": precision_micro,
        "precision_weighted": precision_weighted,
        "recall_macro": recall_macro,
        "recall_micro": recall_micro,
        "recall_weighted": recall_weighted,
    }

model_name = "Albertina"
model_path = "PORTULAN/albertina-100m-portuguese-ptbr-encoder"

CHECKPOINT_DIR = "/content/fold_checkpoints"
OOF_DIR = "/content/oof_results"

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(OOF_DIR, exist_ok=True)

kf = KFold(n_splits=5, shuffle=True, random_state=42)

oof_preds = np.zeros((len(X_train), len(emotions)))
oof_labels = y_train.values.copy()

tokenizer = AutoTokenizer.from_pretrained(model_path)

def tokenize(batch):
  return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

for fold, (train_idx, val_idx) in enumerate(kf.split(X_train)):
  fold_dir = f"{CHECKPOINT_DIR}/fold_{fold}"
  os.makedirs(fold_dir, exist_ok=True)

  oof_path = f"{fold_dir}/oof_preds.npy"
  idx_path = f"{fold_dir}/val_idx.npy"

  if os.path.exists(oof_path) and os.path.exists(idx_path):
    print(f"Fold {fold} já processado. Pulando...")

    saved_preds = np.load(oof_path)
    saved_idx = np.load(idx_path)

    oof_preds[saved_idx] = saved_preds
    continue

  print(f"Processando fold {fold}...")

  X_tr = X_train.iloc[train_idx]
  X_val = X_train.iloc[val_idx]

  y_tr = y_train.iloc[train_idx]
  y_val = y_train.iloc[val_idx]

  beta = 0.999
  samples_per_class = np.sum(y_tr.values, axis=0)
  effective_num = 1.0 - np.power(beta, samples_per_class)
  weights = (1.0 - beta) / effective_num
  weights = weights / np.sum(weights) * len(weights)

  train_ds = Dataset.from_dict({
    "text": X_tr.tolist(),
    "labels": y_tr.values.tolist()
  })

  val_ds = Dataset.from_dict({
    "text": X_val.tolist(),
    "labels": y_val.values.tolist()
  })

  train_ds = train_ds.map(tokenize, batched=True)
  val_ds = val_ds.map(tokenize, batched=True)

  train_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
  val_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

  model = AutoModelForSequenceClassification.from_pretrained(
      model_path,
      num_labels=len(emotions)
  )

  model = model.float()

  args = TrainingArguments(
      output_dir=fold_dir,
      eval_strategy="epoch",
      save_strategy="epoch",
      learning_rate=2e-5,
      per_device_train_batch_size=16,
      per_device_eval_batch_size=16,
      num_train_epochs=8,
      weight_decay=0.01,
      load_best_model_at_end=True,
      metric_for_best_model="f1_macro",
      logging_steps=100,
      report_to="none",
      fp16=False,
      bf16=False,
      torch_compile=False,
      lr_scheduler_type="linear",
      warmup_ratio=0.2
  )

  trainer = CBTrainer(
      model=model,
      args=args,
      train_dataset=train_ds,
      eval_dataset=val_ds,
      compute_metrics=compute_metrics,
      class_weights=weights
  )

  trainer.train()

  trainer.save_model(f"{fold_dir}/model")

  preds_output = trainer.predict(val_ds)

  logits = preds_output.predictions
  probs = torch.sigmoid(torch.tensor(logits)).numpy()

  oof_preds[val_idx] = probs

  np.save(oof_path, probs)
  np.save(idx_path, val_idx)
  np.save(f"{fold_dir}/logits.npy", logits)

  print(f"Fold {fold} concluído!")

np.save(f"{OOF_DIR}/oof_preds_full.npy", oof_preds)
np.save(f"{OOF_DIR}/oof_labels_full.npy", oof_labels)

df_meta = pd.DataFrame(oof_preds, columns=emotions)
df_meta["original_index"] = X_train.index

for i, emo in enumerate(emotions):
  df_meta[f"label_{emo}"] = oof_labels[:, i]

df_meta.to_csv(f"{OOF_DIR}/meta_dataset.csv", index=False)