# -*- coding: utf-8 -*-
"""Testing_BERTs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wco7wbX1Ktl2G2qpOIWpzk62ixeGuTmv
"""

!pip install -q transformers datasets accelerate scikit-learn torch reportlab

import os
import json
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F

from google.colab import files

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

df = pd.read_csv("/content/go_emotions_treated.csv")

df['BASE_TEXT_PT'] = df['BASE_TEXT_PT'].fillna("").astype(str)

emotions = [
    'admiration','amusement','anger','annoyance','approval','caring',
    'confusion','curiosity','desire','disappointment','disapproval',
    'disgust','embarrassment','excitement','fear','gratitude','grief',
    'joy','love','nervousness','optimism','pride','realization','relief',
    'remorse','sadness','surprise','neutral'
]

X = df["BASE_TEXT_PT"]
y = df[emotions]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.8, random_state=42
)

beta = 0.999

samples_per_class = np.sum(y_train.values, axis=0)
effective_num = 1.0 - np.power(beta, samples_per_class)
weights = (1.0 - beta) / effective_num
weights = weights / np.sum(weights) * len(weights)

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    probs = 1 / (1 + np.exp(-logits))
    preds = (probs > 0.5).astype(int)

    precision_macro, recall_macro, f1_macro, _ = precision_recall_fscore_support(
        labels, preds, average="macro"
    )

    precision_micro, recall_micro, f1_micro, _ = precision_recall_fscore_support(
        labels, preds, average="micro"
    )

    precision_weighted, recall_weighted, f1_weighted, _ = precision_recall_fscore_support(
        labels, preds, average="weighted"
    )

    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "f1_macro": f1_macro,
        "f1_micro": f1_micro,
        "f1_weighted": f1_weighted,
        "precision_macro": precision_macro,
        "precision_micro": precision_micro,
        "precision_weighted": precision_weighted,
        "recall_macro": recall_macro,
        "recall_micro": recall_micro,
        "recall_weighted": recall_weighted,
    }

class CBTrainer(Trainer):
    def __init__(self, class_weights, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = torch.tensor(class_weights).float()

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=0):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        device = logits.device
        labels = labels.float().to(device)
        weights = self.class_weights.to(device)

        weights_for_samples = weights.unsqueeze(0) * labels
        weights_for_samples = weights_for_samples.sum(1).unsqueeze(1)
        weights_for_samples = weights_for_samples.repeat(1, labels.size(1))

        loss = F.binary_cross_entropy_with_logits(
            logits, labels, weight=weights_for_samples
        )

        return (loss, outputs) if return_outputs else loss

models = {
    # "BERTimbau": "neuralmind/bert-base-portuguese-cased",
    # "XLM-RoBERTa": "FacebookAI/xlm-roberta-base",
    # "mBERT": "bert-base-multilingual-cased",
    "Albertina": "PORTULAN/albertina-100m-portuguese-ptbr-encoder"
}

kf = KFold(n_splits=5, shuffle=True, random_state=42)

results = []
all_results = []

CHECKPOINT_DIR = "/content/fold_checkpoints"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

torch.cuda.empty_cache()

for model_name, model_path in models.items():
    print(f"\n===== {model_name} =====")

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    fold_metrics = []

    for fold_idx, (train_idx, val_idx) in enumerate(kf.split(X_train)):
        checkpoint_path = os.path.join(
            CHECKPOINT_DIR,
            f"{model_name}_fold_{fold_idx}.json"
        )

        if os.path.exists(checkpoint_path):
            print(f"Fold {fold_idx} já processado. Pulando...")

            with open(checkpoint_path, "r") as f:
                metrics = json.load(f)

            fold_metrics.append(metrics)
            all_results.append({
                "model": model_name,
                "fold": fold_idx,
                **metrics
            })
            continue

        print(f"Fold {fold_idx}")

        X_tr, X_va = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_tr, y_va = y_train.iloc[train_idx], y_train.iloc[val_idx]

        df_tr = pd.DataFrame({"text": X_tr, "labels": y_tr.values.tolist()})
        df_va = pd.DataFrame({"text": X_va, "labels": y_va.values.tolist()})

        train_ds = Dataset.from_pandas(df_tr)
        val_ds = Dataset.from_pandas(df_va)

        def tokenize(batch):
            return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

        train_ds = train_ds.map(tokenize, batched=True)
        val_ds = val_ds.map(tokenize, batched=True)

        train_ds.set_format("torch")
        val_ds.set_format("torch")

        model = AutoModelForSequenceClassification.from_pretrained(
            model_path,
            num_labels=len(emotions)
        )

        # for Albertina
        model = model.float()

        args = TrainingArguments(
            output_dir=f"./results_{model_name}",
            eval_strategy="epoch",
            save_strategy="epoch",
            learning_rate=2e-5,
            per_device_train_batch_size=16,
            per_device_eval_batch_size=16,
            num_train_epochs=12,
            weight_decay=0.01,
            load_best_model_at_end=True,
            metric_for_best_model="f1_macro",
            logging_steps=100,
            report_to="none",
            fp16=False,
            bf16=False,
            torch_compile=False,
            lr_scheduler_type="linear",
            warmup_ratio=0.2
        )

        trainer = CBTrainer(
            model=model,
            args=args,
            train_dataset=train_ds,
            eval_dataset=val_ds,
            compute_metrics=compute_metrics,
            class_weights=weights
        )

        trainer.train()
        metrics = trainer.evaluate()

        with open(checkpoint_path, "w") as f:
            json.dump(metrics, f)

        files.download(checkpoint_path)

        fold_metrics.append(metrics)

        result = {
            "model": model_name,
            "fold": fold_idx,
            **metrics
        }

        all_results.append(result)

    # média dos folds
    avg_metrics = {
        k: np.mean([fm[k] for fm in fold_metrics])
        for k in fold_metrics[0].keys()
    }

    avg_metrics["model"] = model_name
    results.append(avg_metrics)

df_all_results = pd.DataFrame(all_results)
df_all_results = df_all_results.sort_values(["model", "fold"])

df_all_results.to_csv("/content/fold_results.csv", index=False)

print("Arquivo salvo em /content/fold_results.csv")

df_results = pd.DataFrame(results)
df_results = df_results.sort_values("eval_f1_macro", ascending=False)
df_results

doc = SimpleDocTemplate("/content/results.pdf")
styles = getSampleStyleSheet()

content = []
content.append(Paragraph("Resultados CV dos Modelos BERT", styles["Title"]))
content.append(Spacer(1, 12))

for _, row in df_results.iterrows():
    text = f"""
    Modelo: {row['model']}<br/>
    Accuracy: {row['eval_accuracy']:.4f}<br/>
    <br/>
    Precision Macro: {row['eval_precision_macro']:.4f}<br/>
    Precision Micro: {row['eval_precision_micro']:.4f}<br/>
    Precision Weighted: {row['eval_precision_weighted']:.4f}<br/>
    <br/>
    Recall Macro: {row['eval_recall_macro']:.4f}<br/>
    Recall Micro: {row['eval_recall_micro']:.4f}<br/>
    Recall Weighted: {row['eval_recall_weighted']:.4f}<br/>
    <br/>
    F1 Macro: {row['eval_f1_macro']:.4f}<br/>
    F1 Micro: {row['eval_f1_micro']:.4f}<br/>
    F1 Weighted: {row['eval_f1_weighted']:.4f}<br/>
    """

    content.append(Paragraph(text, styles["Normal"]))
    content.append(Spacer(1, 12))

doc.build(content)

print("PDF gerado em /content/results.pdf")